config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :classifications
  resources :genders
  resources :countries
  devise_for :users
  get 'welcome/index'
  root :to =>"welcome#index"
  
  get '/movies/:id', to: 'movies#show', as: 'movie1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
   # @movie = Movie.where(:rating => 2)
   
      @movie = Movie.find(params[:id])
  end
  
  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :premiere_date, :director, :country_id, :cast, :gender_id, :classification_id, :description, :rating, :film)
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <table>
  <tbody><div class="field">
    <tr>
    
    <th><%= form.label :title %></th>
    <th></th>
    <th><%= form.text_field :title, id: :movie_title %></th>
    </tr>
    <tr>
    <th><%= form.label :premiere_date %></th>
    <th></th>
    <th><%= form.text_field :premiere_date, id: :movie_premiere_date %></th>
    </tr>
    <tr>
      <th><%= form.label :director %></th>
      <th></th>
      <th><%= form.text_field :director, id: :movie_director %></th>
    </tr>
    <tr>
      <th><%= form.label :country_id %><th>
      <th><%= form.collection_select :country_id, Country.all, :id, :name %></th>
    </tr>
    <tr>
      <th><%= form.label :cast %><th>
      <th><%= form.text_area :cast, id: :movie_cast %></th>
    </tr>
    <tr>
      <th><%= form.label :gender_id %><th>
      <th><%= form.collection_select :gender_id, Gender.all, :id, :name %></th>
    </tr>
    <tr>
      <th><%= form.label :classification_id %><th>
      <th><%= form.collection_select :classification_id, Classification.all, :id, :name %></th>
    </tr>
    <tr>
      <th><%= form.label :description %><th>
      <th><%= form.text_area :description, id: :movie_description %></th>
    </tr>
    <tr>
      <th><%= form.label :rating %><th>
      <th><%= form.number_field :rating, id: :movie_rating %></th>
    </tr>
    <tr>
      <th><%= form.label :film %><th>
      <th><%= form.number_field :film, id: :movie_film %></th>
    </tr>
    </div>
</tbody>
</table>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/find.html.erb
<p id="notice">Search<%= notice %></p>
<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Premiere</th>
      <th>Director</th>
      <th>Country  </th>
      <th>Cast</th>
      <th>Gender</th>
      <th>Classification</th>
      <th>Description</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.premiere_date %></td>
        <td><%= movie.director %></td>
        <td><%= movie.country.name %></td>
        <td><%= movie.cast %></td>
        <td><%= movie.gender.name %></td>
        <td><%= movie.classification.name %></td>
        <td><%= movie.description %></td>
        <td><%= movie.rating %></td>
        
        </tr>
        <tr>
          <td><%= link_to 'Show', movie %></td>
          <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
          <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Search', movie %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movies</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Premiere date</th>
      <th>Director</th>
      <th>Country</th>
      <th>Cast</th>
      <th>Gender</th>
      <th>Classification</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Film</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.title %></td>
        <td><%= movie.premiere_date %></td>
        <td><%= movie.director %></td>
        <td><%= movie.country %></td>
        <td><%= movie.cast %></td>
        <td><%= movie.gender %></td>
        <td><%= movie.classification %></td>
        <td><%= movie.description %></td>
        <td><%= movie.rating %></td>
        <td><%= movie.film %></td>
        <td><%= link_to 'Show', movie %></td>
        <td><%= link_to 'Edit', edit_movie_path(movie) %></td>
        <td><%= link_to 'Destroy', movie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie', new_movie_path %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Premiere date:</strong>
  <%= @movie.premiere_date %>
</p>

<p>
  <strong>Director:</strong>
  <%= @movie.director %>
</p>

<p>
  <strong>Country:</strong>
  <%= @movie.country.name %>
  
</p>

<p>
  <strong>Cast:</strong>
  <%= @movie.cast %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @movie.gender.name %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @movie.classification.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @movie.rating %>
</p>

<p>
  <strong>Film:</strong>
  <%= @movie.film %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>