config/routes.rb
Rails.application.routes.draw do
  resources :movies
  resources :classifications
  resources :genders
  resources :countries
  devise_for :users
  get 'welcome/index'
  root :to =>"welcome#index"
  
  get '/movies/:id', to: 'movies#show', as: 'movie1'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movie Library</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>

  <div id="login">
  <% if user_signed_in? %>
  Login as <strong><%= current_user.email %></strong>.
  <%= link_to 'Modificar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

      </div>
      
      <h1 id="titulo">
      <%= image_tag("logo2.png",width:'10%') %>
      <%= image_tag("letras.png",width:'30%') %>
      <%= image_tag("omni2.png",width:'12%') %>
      </h1>
    </header>
    <main id="principal">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

 <div id="menuprincipal">
 <% if user_signed_in? %>
      <input type="checkbox" id="css3menu-switcher" class="c3m-switch-input">
      <ul id="css3menu0" class="topmenu">    
        <li class="switch"><label onclick="" for="css3menu-switcher"></label></li>
        <li class="topfirst"><%= link_to 'Home', welcome_index_path %></li>
        <li class="topfirst"><a href="#" style="width:140px;"><span>Catalogue</span></a>
        <ul>

          <li class="subfirst"><%= link_to 'Movie Countries', countries_path %></li>
          <li class="subfirst"><%= link_to 'Movie Genres', genders_path %></li>
          <li class="subfirst"><%= link_to 'Movie Classifications', classifications_path %></li>
        </ul></li>
        <li class="topfirst"><%= link_to 'Movie', movies_path %></li>
        <li class="topfirst"><%= link_to 'Profile', edit_user_registration_path %></li>
        <li class="topfirst"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>   </li>  
      </ul>
      <% end %>
 </div>
      <div id="contenido" >
          <%= yield %>
      </div>
    </main>
  </body>
</html>